name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/MohamedDevvv/android_kernel_lenovo_msm8937
          kernel-branch: lineage-18.1
          config: karatep_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          android-version: 11
          aosp-clang-version: r383902
          android-ndk: false
          android-ndk-version: false
