name: test

on:
  push:
    branches: [ "lineage-18.1" ]
  pull_request:
    branches: [ "lineage-18.1" ]

jobs:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: test
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/MohamedDevvv/android_kernel_lenovo_msm8937
          kernel-branch: lineage-18.1
          config: karatep_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 11
          aosp-clang-version: r383902
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
